### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by BLepers** [milesgranger/elevation-api#29]
Would it be possible to make the elevation API accessible via javascript? Currently I get a Cross-Origin error:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://elevation-api.io/api/elevation?points=...
```

I think this could easily be fixed by adding a .htaccess containing:
```
Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Headers "Content-Type"
Header set Access-Control-Allow-Methods "GET"
```

Thanks :)

**Comment by milesgranger** [comment]
Ah, seems silly now, but I didn't even think about adding this. I'll try and get this adjusted by the end of the day. :+1:

**Comment by milesgranger** [comment]
Hi @BLepers, thanks again for letting me know about this! 
Should be fixed now, let me know if otherwise.
